# Generated by Django 3.0.8 on 2020-08-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='avaliação criada em')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('height', models.FloatField(verbose_name='Altura')),
                ('bf', models.FloatField(verbose_name='BF')),
                ('pathology', models.TextField(verbose_name='Patologia')),
                ('objective', models.TextField(verbose_name='Objetivo')),
                ('conditioning', models.TextField(verbose_name='Condicionamento Fisico')),
            ],
        ),
    ]
